### ISSUE TITLE
put it on fdroid

### ISSUE THREAD

**Issue by plumpudding** [gateship-one/malp#1]
Also a reminder for me to make the suggestion on the fdroid side

**Comment by djselbeck** [comment]
Yes, I would love this. Template should be similar to the Odyssey one :)

**Comment by djselbeck** [comment]
I'll try this with the next version (1.0.9)

**Comment by djselbeck** [comment]
Progress here: https://f-droid.org/forums/topic/m-a-l-p-mpd-client/

**Comment by djselbeck** [comment]
Released: https://f-droid.org/repository/browse/?fdid=org.gateshipone.malp
