### ISSUE TITLE
Connection problems and failure 3/0: incorrect password 

### ISSUE THREAD

**Issue by ruddyshock** [gateship-one/malp#101]
After updating to version 1.1.13 MALP loses connection to my MPD on my raspberry pi 3 showing "Failure 3/0: incorrect password". I can browse my files and play music a few seconds, then the bug(?) appears. Pressing "play" again continues playing music for a few seconds. The password is correct, setting another password doesn't help.

LogCat says: MPD error: ACK [3@0] {password} incorrect password

**Comment by djselbeck** [comment]
Behaviour changed with the new MALP version.

Either enter a correct password for your MPD or none at all

**Comment by ruddyshock** [comment]
Checked my mpd.conf again. Set new password. Now it works.
Thanks for your support.
