### ISSUE TITLE
Add directory not working in M.A.L.P

### ISSUE THREAD

**Issue by sahmmie** [gateship-one/malp#108]
#### Expected behavior
I tried adding song from my various directory, so i went to files then clicked add director, it was suposed to pop up my storage directories and folders

#### Actual behavior
when i click the add directory nothing happened
#### How to reproduce
it can be downloaded from f-droid [Download](https://f-droid.org/packages/org.gateshipone.malp/)

launch the app, click the 3 lines you see by the left, click the files, click the cross icon.

Device Used: Infinix Note 3 or Infinix X601
Operating system: Android 7.0 Nougat
app Version: 1.1.14 (23)

#### Recording Of The Bug
<iframe width="560" height="315" src="https://www.youtube.com/embed/irYFW56NpzY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@sahmmie/add-directory-not-working-in-m-a-l-pp">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by djselbeck** [comment]
Your MALP instance is not connected to any MPD server which can be seen by the MALP text in the navdrawer. It should be the name of the connected profile.

Did you configure your MPD profile correctly?

**Comment by djselbeck** [comment]
Closing. I don't want any business with Utopian.io. Please refrain from using it again on our projects.

**Comment by sahmmie** [comment]
I guess i connected it correctly!


On 24 Feb 2018 4:42 pm, "Hendrik Borghorst" <notifications@github.com>
wrote:

Closed #108 <https://github.com/gateship-one/malp/issues/108>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gateship-one/malp/issues/108#event-1490472524>, or mute
the thread

**Comment by sahmmie** [comment]
Okay, thank you!
