### ISSUE TITLE
Adding albums to playlist sometimes fails partially: Space expected after closing ""

### ISSUE THREAD

**Issue by chrsmrtnx** [gateship-one/malp#109]
When adding certain albums in my collection to the playlist, I get an error:

> Error 5/7: Space expected after closing ""

The result is that only some of the tracks in the album are added to the playlist. Usually the first few tracks are added fine, then MALP hits the problem and stops. What is the problem? Best I can tell, it's track names that include quotation marks.

So, for instance, the album that produces the above error has 9 tracks, the 8th of which contains quotation marks. When you add that album to the playlist, only the first 7 tracks are added - the last two aren't.

To be clear, "5/7" is just an example - different albums yield different numbers. When I try to add an album where all but the last of 5 tracks has quotation marks in the name, I get "Error 5/0: Space exected after..." etc. and no tracks are added. Curiously, if the title of the album has quotation marks, there doesn't appear to be a problem - it's the track names that trip things up.

**Comment by djselbeck** [comment]
Should be fixed with the aforementioned commit.
