### ISSUE TITLE
show active profile near app title

### ISSUE THREAD

**Issue by bjo81** [gateship-one/malp#11]
I find it difficult to see which profile is active. Maybe the active profile could be shown near the app title.

**Comment by djselbeck** [comment]
Good point, thought about it a while ago but forgot it or I was to lazy :). It is implemented with commit: 22c5ff149545befe05e2cf1a660a663f2ee6b852

**Comment by djselbeck** [comment]
Released

**Comment by bjo81** [comment]
Thanks.
