### ISSUE TITLE
FR: Download songs

### ISSUE THREAD

**Issue by gerroon** [gateship-one/malp#111]
Hi

It would be so nice if one could download songs individually or a whole playlist  to the device  to a predefined media download folder organized under artst/album.

thanks

**Comment by djselbeck** [comment]
That is technically not possible because MPD does not provide a download feature.

**Comment by gerroon** [comment]
Yeah I can see that, I was more maybe thinking some automatic saving of streams while replcating the metadata. I guess that would be an involved thing.

**Comment by djselbeck** [comment]
Closing this as it is not really feasible and out of scope for MALP. There are other tools to synchronize or download music available.
