### ISSUE TITLE
Feature request: Save current playlist to a physical file

### ISSUE THREAD

**Issue by emgeebee** [gateship-one/malp#116]
MALP should save the current playlist to a physical playlist file (m3u) with a configurable name. This would facilitate "resume" type behaviour when restarting the server if a playlist existed with what was currently in the queue. A client, seeing that the server was back online, could tell the server to play "currently-playing.m3u".

For my own usecase of this feature, I'm using MALP with a Chord Poly - a portable MPD server which gets restarted several times a day. I'd like to script (using tasker, or similar) resuming what was previously playing when the server comes back online.

**Comment by djselbeck** [comment]
MPD already has this feature: [Documentation](https://www.musicpd.org/doc/user/config_other.html#idm458)

I'm not willing to implement workarounds for lousy configured MPD servers ;)

**Comment by emgeebee** [comment]
Nice - didn't know this! Will chase the server guys 👍
