### ISSUE TITLE
 new logo for M.A.L.P

### ISSUE THREAD

**Issue by damahboy** [gateship-one/malp#121]
Hi PO
I am today creating and proposing a new logo design for MALP, this logo is a gift from me for my sense of concern to the world of OP, especially for the project MALP itself, I am happy to make it, this design takes approximately 8 hours of manufacture, helpful, if you're happy I can give you his PR file for you MALP: D
![1](https://user-images.githubusercontent.com/38080324/38916740-c274d914-4312-11e8-9ed6-f42285ea3b3d.png)
![2](https://user-images.githubusercontent.com/38080324/38916762-ce1174ee-4312-11e8-9ca0-6745da4c54d5.png)

**Comment by ikorb** [comment]
I'm not the one to decide this, but I think I would prefer the current icon to this one.

**Comment by damahboy** [comment]
ok sir .. hehe thank you very much
