### ISSUE TITLE
Add Soundcloud URL

### ISSUE THREAD

**Issue by donpatrice** [gateship-one/malp#125]
How can I add a Soundcloud URL to the playlist. With mpc it works like this:

```
mpc load soundcloud://url/https://soundcloud.com/foo/bar
```

But it doesn't with M.A.L.P.

Thanks a lot!

**Comment by djselbeck** [comment]
Can you give me a concrete example? Because I tried the one you provided and MPD received the correct one.

The log was:

`client: [0] process command "add "soundcloud://url/https://soundcloud.com/foo/bar""
exception: Unsupported URI scheme
`

**Comment by donpatrice** [comment]
And if try:

```
soundcloud://url/https://soundcloud.com/tiefmusic/axel-boman-we-are-the-keys
```

I get:

```
May 06 18:27 : playlist: Unsupported URI scheme
```

**Comment by djselbeck** [comment]
mpc load is different from MALPs add URI. Uri adds an URI to a playlist. mpc load loads an playlist with the given path. At the moment there is no support to add arbitrary playlists. I mark this as a FR

**Comment by donpatrice** [comment]
Thanks a lot.

Am 6. Mai 2018 18:34:01 MESZ schrieb Hendrik Borghorst <notifications@github.com>:
