### ISSUE TITLE
MPD Proxy setting and Error 2/0: Bad song index

### ISSUE THREAD

**Issue by mxjeff** [gateship-one/malp#129]
Hi

Trying to add an artist or album from the library view I get an error `Error 2/0: Bad song index`.

The only way I managed to add a song is track by track in the search view.
From the search view trying to add an artist or an album is failing as well.

I'm running MPD 0.19.21 on armhf.
My music library is tagged with MusicBrainzID.
MALP 1.1.15 (f-droid)

**Comment by mxjeff** [comment]
I have two MPD running on my domestic setup.
One on my NAS and one on RaspBerry ([using the NAS database thanks to the proxy plugin](https://www.musicpd.org/doc/user/advanced_config.html)).

Both MPD are 0.19.21 (the one on the NAS is an amd64 Debian stretch build).

Indeed, MALP is running fine on the NAS MPD server, I have the issue against the raspberry server only (and with MALP client only so far, cannot reproduce something similar with ncmp for instance).

The only difference between the servers is the database setting (apart from the architecture).

The MPD server on my raspberry is open on IPv6, I can give you access to try to reproduce.

> Can you precisely explain what actions cause this?

- open MALP
- in the Artist view
- long touch to open contextual menu
- select "play albums"

→ It triggers `Error 2/0: Bad song index`

Here are screenshots :

1. [Select artist](https://media.kaliko.me/Screenshot_M.A.L.P._20180526-194237.png)
2. [error](https://media.kaliko.me/Screenshot_M.A.L.P._20180526-194248.png)

Hope this helps
Cheers

**Comment by djselbeck** [comment]
I think there are two possible causes.

The first could be that the Raspberry Pi is to slow to provide a list of artist albums or to process all the requests to add albums within the 5 second timeout of MALP and some commands are not executed properly.

The second cause could be within the proxy plugin. To test this I need to setup a test setup which I may do in time but can not provide a time frame at the moment because my temporal resources are spread very thin at the moment.

Thanks for the offering of an access to your RPi but unfortunately my ISP is unable to provide an IPv6 access over an business-grade contract :angry:

**Comment by djselbeck** [comment]
I was able to setup a testsetup with two instances of mpd 0.19.21 running (one of them connected as a proxy). Play/Add Artist seems to work though.

So maybe it is a timeout error.

**Comment by mxjeff** [comment]
Hi

I did upgrade both servers to 0.20.21 (commit [8dcb1f8](https://github.com/MusicPlayerDaemon/MPD/commit/8dcb1f805d39efef31ea63d5c42af9eb6263712f)) with my own Debian package build (with official libmpdclient 2.9 from stretch).

Now I've got another error on both artists and albums view: `Error 5/0: Grouping requires libmpdclient 2.12`

Everything if fine with MALP against the master MPD server (DB host).

Here are debian stretch backported packages:

- raspbian : [mpd_0.20.21-1~1527694515_armhf.deb](https://media.kaliko.me/mpd_0.20.21-1~1527694515_armhf.deb)
- debian stretch : [mpd_0.20.21-1~1527694515_amd64.deb](https://media.kaliko.me/mpd_0.20.21-1~1527694515_amd64.deb)

**Comment by mxjeff** [comment]
Al right this is now fixed with latest MPD (commit [8dcb1f8](https://github.com/MusicPlayerDaemon/MPD/commit/8dcb1f805d39efef31ea63d5c42af9eb6263712f) unreleased yet) **and** libmpdclient >= 2.12.

I did build latest mpdclient package for Debian and raspbian (armhf) Stretch release.
Upgrading to 2.14 fixes the previous error: https://media.kaliko.me/deb/mpd/libmpdclient2.14/

I guess we could close the issue then.
Cheers
