### ISSUE TITLE
bug found in M.A.L.P app (  when i install the application some error installing )

### ISSUE THREAD

**Issue by nasirshah1813** [gateship-one/malp#130]
#### Project Information

* Repository:  https://github.com/gateship-one/malp

* Project Name:  M.A.L.P.

* Publisher   : gateship-one

#### Expected behavior
according to my knowledge when i try to install the  M.A.L.P app the application should be install in my phone easily  

#### Actual behavior
after open the fdroid stor when i try to install the M.A.L.P application the M.A.L.P app cannot install in my device and error come  some error installing  in sdk of apk is lower 

#### How to reproduce
* [download ](https://f-droid.org/packages/org.gateshipone.malp/)application 
* try to install the application 
* note the bug 
* Browser:   M.A.L.P app Version 1.1.15 
 * Operating system: android version 4.4.2
 

#### Recording Of The Bug
https://youtu.be/0uhWySRJKvU

#### Proof of Work Done   
https://github.com/nasirshah1813

**Comment by djselbeck** [comment]
Android 5.0 and upwards is required
