### ISSUE TITLE
How does the pseudo-artist "no_artist_tag" work?

### ISSUE THREAD

**Issue by mueller-ma** [gateship-one/malp#28]
I have many albums under no-artist-tag, however they are also under the right artist. When I tab on one of these songs I can see that it has the right values for artist and albumArtist
Is this a bug?

**Comment by djselbeck** [comment]
It worked for old filtering and got lost on the way. Empty artist is now filtered out:

8e4307f0f82cb862841fc8bb66a1aebb6d1002a9
