### ISSUE TITLE
Better handling for wikipedia 404 error

### ISSUE THREAD

**Issue by mueller-ma** [gateship-one/malp#29]
What about trying the system locale wikipedia and when getting 404 try the english one. When getting a 404 again display "no wikipedia article found".

**Comment by djselbeck** [comment]
We are not querying the wikipedia. We are only calling an open on the URL. Everything after that is handled by either the webbrowser and wikipedias website or the wikipedia application.

Also the feature is more like a gimmick for a quick link. Closing this.
