### ISSUE TITLE
[FR] Add Launcher widget

### ISSUE THREAD

**Issue by lyndametref** [gateship-one/malp#3]
I am not sure if I missed it, but if it is not there it would be nice to have some widget for the basic control (play, pause, fwd, ...)

**Comment by djselbeck** [comment]
Not yet implemented. May be added in the future. Thought about it but needs some refactoring and major changes to some of the networking stuff as MALP is using 3 networkconnections at the moment to keep responsive.

Should reduce this for a widget to not reach MPDs default limit (10 connections?).

**Comment by djselbeck** [comment]
Will be part of the next release. Preliminary version is in [widget branch](https://github.com/gateship-one/malp/tree/widget).

**Comment by lyndametref** [comment]
Thank you very much!

**Comment by djselbeck** [comment]
Release with 1.1.0
