### ISSUE TITLE
Impossible to change language

### ISSUE THREAD

**Issue by Choukajohn** [gateship-one/malp#37]
Hi,
Apparently there's French translation available but I can't change language in app and there is no automatic detection.

**Comment by mueller-ma** [comment]
This commit a869780a5457979b5241ca550f3baa9c3fcb0509 fixes the french translation and there is currently no release with this fix

**Comment by Choukajohn** [comment]
OK thx for information.
So I just need to wait for the next release.

**Comment by djselbeck** [comment]
I've just uploaded the version to google play. It should be available over F-Droid in a few days.

Sorry for the delay. Planned to release it with the streaming feature but it takes more time.

**Comment by Choukajohn** [comment]
Nice thank you !
What is exactly the streaming feature you are talking about?

**Comment by djselbeck** [comment]
Playback of HTTP streams of MPD on the android device itself:

#14

**Comment by Choukajohn** [comment]
Ho nice ! I tried to do this a few days ago and understood that it was only possible through a browser. 
Thanks again for your work.
