### ISSUE TITLE
[FR] add option to show only albumartist

### ISSUE THREAD

**Issue by fabsmusicjunkie** [gateship-one/malp#4]
In mpdroid you have the option to show albumartist instead of artists, this is quite good for compilations and albums. Musicbrainz uses Artist Tag for feat., which results in many artists with only one song.

**Comment by djselbeck** [comment]
Should be easy to implement. Will check this for the next version.

**Comment by djselbeck** [comment]
b10eb261f825607cb0962ed78722119e9a66d0d9 implemented this as a option

**Comment by djselbeck** [comment]
Release with 1.1.0
