### ISSUE TITLE
Can control but no stream

### ISSUE THREAD

**Issue by aureooms** [gateship-one/malp#43]
Can connect, play, pause etc. but the app does not output any sound.
Stream can be listened to in phone browser though.
Any obvious thing I missed?
I have the same problem with MPDroid.

Running OxygenOS 3.5.4.
Android 6.0.1.
MPD server port is 5800 and configured as such.
HTTP stream port is 5900 (but cannot find where to configure that).
Audio output settings
```
audio_output {
    type		"httpd"
    name		"http stream"
    encoder		"lame"		# optional, vorbis or lame
    port		"5900"
    bind_to_address	"0.0.0.0"		# optional, IPv4 or IPv6
    bitrate		"128"			# do not define if quality is defined
    format		"44100:16:1"
    max_clients	"0"			# optional 0=no limit
}
```

**Comment by djselbeck** [comment]
The feature is not yet released. You probably don't have the right branch installed.
