### ISSUE TITLE
Possibility to hide separators in play queue

### ISSUE THREAD

**Issue by berz** [gateship-one/malp#46]
At the moment there are visible separators between albums in the play queue. This can be useful when listening to complete albums. But sometimes I want to listen to my music as singles: track 6 on album A, followed by track 2 on album B ... When listening this way a separator is displayed before every track:

<img src="https://cloud.githubusercontent.com/assets/2106809/24549951/26ae0f92-161c-11e7-9ab4-6adcd241c90a.png" width="250px">

Because of this only 3 tracks get displayed and there is a lot of visual clutter.

I now fall back to using MPDroid when listening to music as singles. While it lacks a lot of niceties that malp has its playlist view is more clear and compact, managing to display 8 tracks instead of malp's 3.

<img src="https://cloud.githubusercontent.com/assets/2106809/24550184/47f6be00-161d-11e7-8b04-7a143c7da712.png" width="250px">

I would really like it if mamp could display the play queue like in the screenshot above, for example by giving me the choice between an album view and a singles view or dropping the separator altogether.

**Comment by djselbeck** [comment]
Disabling it all together is not an option for me.

Perhaps a minimal section length could be implemented, but I've to check for performance penalties first.

**Comment by mueller-ma** [comment]
Reduce the size of the speaker icon would free up space too. IMO it is larger than it should be

**Comment by berz** [comment]
Having the app determine whether I am listening to singles or albums and adjusting the way the play queue is displayed accordingly would be even better than having to manually switch between them.

Only displaying the separator if the next three tracks have the same album tag would work.

**Comment by djselbeck** [comment]
> Reduce the size of the speaker icon would free up space too. IMO it is larger than it should be

This would help nothing at all. The speaker is as big as it is to give some space around the seekbar, to prevent accidental wrong volumes. (I have my power amplification directly connected to the PC output)

> Only displaying the separator if the next three tracks have the same album tag would work.

That's what I've said above to check if it is feasible.

**Comment by djselbeck** [comment]
Tested it. It looks unpleasingly for me as it pretends wrong sections to the user.

![image72](https://cloud.githubusercontent.com/assets/1886122/24698691/d988e7b2-19f1-11e7-9b3e-149cf04971f4.png)

**Comment by djselbeck** [comment]
Disabling is also not really an option as functionality depends on it "removal of a whole album"

**Comment by djselbeck** [comment]
e2f1bd6f06066a1076a4986c6278e0f86bc46007 and 123b0a76e1216514f002903e95b6ced6eeed251e implemented this as an option
