### ISSUE TITLE
Two small UI improvements

### ISSUE THREAD

**Issue by mueller-ma** [gateship-one/malp#49]
I was using MPDroid and since it isn't developed activly anymore I switched to malp. There are two small thing which are (IMO) better:
When in the libary, tapping on the currently playing song (at the bottom) has the same effect than swiping it to the top:
![screenshot_20170403-165743](https://cloud.githubusercontent.com/assets/22525368/24616003/2f1d0a2c-1890-11e7-8dd8-11c2c90d418a.png)

Swiping left/right has the same effect than tapping on the playlist button:
![screenshot_20170403-165751](https://cloud.githubusercontent.com/assets/22525368/24616043/4bf96456-1890-11e7-8ff2-134d8ba644d3.png)

**Comment by zbits** [comment]
IMHO,
(1) It should be easier to switch between the playlist screen and currently playing screen (as noted above, MPDroid did well with a swipe left/right).
(2) It should more difficult to switch between the currently playing screen and full screen, which I do accidentally all the time.

**Comment by djselbeck** [comment]
To (1) I don't have MPDroid installed so I can't tell. But why is swiping to the playlist in anyway easier than clicking a button? Also I don't want to mix horizontal and vertical drag actions (scrolling in queue vs. swiping between views)

**Comment by mueller-ma** [comment]
1. When using malp with one hand it is easier to swipe somewhere in the middle on the screen than clicking a botton on the top right hand corner
2. MPDroid mixes horizontal and vertical view and it didn't have any problems with that. You can try MPDroid and see how it works

**Comment by djselbeck** [comment]
I'm closing this issue now.

I think the whole idea is misleading and confusing for the user. There is no indication to the user that he can swipe to the side for another view.

To be intuitive something like a tab layout is necessary, which would require to much space in this context. 

If someone can point me to a reference in the official material guidelines indicating that this is a good idea I might reconsider (https://material.io) in the meantime it will stay like it is (consistent with a lot of other music applications)

**Comment by mueller-ma** [comment]
Google Play Music has the first "feature"

**Comment by djselbeck** [comment]
The click to slide up got lost in the rubble. This I might implement
