### ISSUE TITLE
Option to secure client-server control stream with SSL/TLS

### ISSUE THREAD

**Issue by mrplumber** [gateship-one/malp#52]
Hello,
Please consider this scenario when MPD is configured to listen on network facing interfaces. Currently authorization on server is done with plain text passwords which makes it trivial for third party to sniff out. One way around this issue is using SSL/TLS wrapper like stunnel ( https://www.stunnel.org/index.html ). It is not big deal on the server side, but using separate stunnel client on Android device is not optimal since it has to be started before mpd client (M.A.L.P. in this case) and running in the background for duration of use. If optional SSL/TLS support was build in the M.A.L.P. it would eliminate the need for separate stunnel client and improve user experience for those wishing to secure MPD control over their networks.
Best regards,
Mr Plumber

**Comment by djselbeck** [comment]
Not gonna happen. This is out of scope for this application. I'm glad that i don't have to care too much about security as it is.
