### ISSUE TITLE
Feature request: Google Assistant integration

### ISSUE THREAD

**Issue by BLX-S** [gateship-one/malp#58]
I'm going to fork it and see what I can do but this would be absolutely wild. You would be able to ask assistant to play/pause your MALP controls...

**Comment by djselbeck** [comment]
Thanks but I can already tell you that I'm not willing to integrate it unless the libraries that are necessary are completely free as in software.

**Comment by BLX-S** [comment]
@djselbeck I figured, no this isn't what Stallman would approve of. I think it's a play services thing. I'm just gonna tinker around if I find something. Maybe I'll add some other things but I've been using MALP for months now and I just found out it was on GH so my enthousiasm is real...

**Comment by djselbeck** [comment]
The problem is that this would be problematic for the inclusion in F-Droid and it would be against my principles ;) as a strong supporter of open source.

**Comment by BLX-S** [comment]
Ok, I understand. I'll just stick to interface optimisation then ;-) seeing as how I'm a mediocre developer and a better UI designer
