### ISSUE TITLE
Reset Artwork in album resets everything

### ISSUE THREAD

**Issue by rares-p** [gateship-one/malp#59]
Hello,
I want to start by saying this is a cool app and I love it! :D
There are some issues with it that if are fixed this app will be the nirvana of music library management.

One of this issues is when I am in an album and I click Reset Artwork it resets all the artwork for all albums. It would be cool to reset just the artwork for that particular album.

Also, while most of the artwork is correct, there are some misses from time to time. It would be nice after the Reset Artwork button to see a list of the artwork found so I can choose the one that's fit for the album. 
A feature where I can upload my own image to the album would also be a cool thing.

Keep up the good work.
Cheers

**Comment by djselbeck** [comment]
Thanks for reporting this. This is a bug in the SQL statement if no MusicbrainzID is tagged. I'll fix this for the next release

**Comment by rares-p** [comment]
Thanks in advance for fixing it!

**Comment by djselbeck** [comment]
Should be fixed with the next release
