### ISSUE TITLE
Add Korean translation

### ISSUE THREAD

**Issue by parkmino** [gateship-one/malp#60]
Hi!

I came to know M.A.L.P and it looks so promising.
Do you have any plan to implement Korean translation? If not, I'd like to do this as the way I did for MPDroid.
Translating 'https://github.com/gateship-one/malp/blob/master/app/src/main/res/values/strings.xml' into korean would be enough?

**Comment by djselbeck** [comment]
Hi, I have no plan of translating MALP into korean ;-) because I don't speak it.

If you translate it I'm happy to integrate it though. Thanks

**Comment by parkmino** [comment]
OK and I'll back to you with Korean translation.

**Comment by parkmino** [comment]
Please find the Korean(ko) translation as attached.
It's my first draft and more polishing would be necessary in future.
Kindly let me get your any feedback, otherwise, close this issue.
I'll send you any updated Korean translation via your gmail found at github.

Good day!

Minho Park

[strings.xml.zip](https://github.com/gateship-one/malp/files/1175949/strings.xml.zip)

**Comment by djselbeck** [comment]
Thanks. i'll try to integrate it in the next days. If you are familiar with git you could also open an Pull request over github. If not it is also not a problem, just send me the newest version per mail and i'll integrate it.

We usually add translators to the list of contributors. What is the name you want to appear (github nick or realname)?

**Comment by parkmino** [comment]
FYI,

I am 'Minho Park' from Korea and 
<string name="contributor_translator_korean">한국어 번역</string>

Email would be convinient for me if you don't mind.

Thanks

**Comment by djselbeck** [comment]
Released :) thanks again
