### ISSUE TITLE
Allow application to keep running in background.

### ISSUE THREAD

**Issue by MeanEYE** [gateship-one/malp#65]
When pairing MALP with smartwatch everything works great with few minor annoyances. One of them being the fact it stops responding controls from smartwatch (next, previous, play, etc.) the moment screen locks. Ideally we should have an option while player is playing to keep application running in background to allow such control.

**Comment by djselbeck** [comment]
It is currently running as a foreground service. There is not more I can do. With android 8 it even gets worse and the whole Android Doze, and background paranoia always kills MALP.

**Comment by djselbeck** [comment]
It is now running as a foreground service with ongoing notification if MPD playback is running (only on state playing, NOT paused or stopped). This is the most MALP can do to keep running.
