### ISSUE TITLE
Can't connect to mpd server

### ISSUE THREAD

**Issue by ranamalo** [gateship-one/malp#67]
I'm not sure what I'm doing wrong, but I'm unable to connect to my mpd server.  Running 0.19 on ubuntu.  Haven't had issues with any other client.  No errors on the client side, just nothing in library, playlists, etc.  Android 6.0.1. Let me know if you need any other info.

**Comment by djselbeck** [comment]
Works for me with 0.19.21. However I recommend updating MPD to a current version
