### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [gateship-one/malp#68]

**Comment by djselbeck** [comment]
Can you elaborate a bit on this?

**Comment by mueller-ma** [comment]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by djselbeck** [comment]
I'll look into it

**Comment by djselbeck** [comment]
f183d86fb2aaec63689e8371c151689b6505c8ae implemented it
