### ISSUE TITLE
Feature request: Search in library by track name/filename

### ISSUE THREAD

**Issue by mad-ady** [gateship-one/malp#69]
Under Library view one can search by Album and Artist, but there is no way to search for a specific song. I can search for a song inside a playlist, but I have to know in which playlist it is included.

Is there a way to search the library for a song (or ebook) by name, or could you add a new view under library? I'm not sure if adding a new view would be a problem because it would have to load the whole song list...

I love your app and installed it for the Stargate references :)

**Comment by djselbeck** [comment]
Glad you like those references ;).

To load the whole song list is highly discouraged by MPD. You can use the search fragment (search entry in the navdrawer) to use the server based search functionality.

**Comment by mad-ady** [comment]
Sorry for wasting your time. It seems that I'm as smart as Felger and
missed it completely!
Carry on the good work!

**Comment by djselbeck** [comment]
You made my day ;). Thanks for the nice comment
