### ISSUE TITLE
Search type preference

### ISSUE THREAD

**Issue by sellsky** [gateship-one/malp#7]
Every time I open Search dialog, the search type is reset to Track. Can the app remember the last chosen type? Or would it be just better and simplier to put Everything type on top, as it is the most versatile mode?
1.0.8.

**Comment by djselbeck** [comment]
I will implement this for the 1.1.0 release. Thanks for the input.

**Comment by djselbeck** [comment]
Implemented in 25462afcf64900df908f24db00dd32df7b7adf16

**Comment by djselbeck** [comment]
Release with 1.1.0
