### ISSUE TITLE
Password doesn't work with certain special characters

### ISSUE THREAD

**Issue by mrjpaxton** [gateship-one/malp#72]
When I put an apostrophe in my MPD password, for example, then enter in my password in the "Password:" field in the profile entry, it will not connect. (And by the way, it returns no pop-up errors like "failed to connect", so I've been wondering what the heck was going on.)

So the expected result is that the password should work with special characters like the apostrophe, since it works just fine with ncmpcpp. When I removed the apostrophe from my password, it M.A.L.P worked correctly.

M.A.L.P so far is a clean UX and efficient MPD remote/streaming client, especially with that OLED theme, and I really look forward to future improvements!

Thank you very much for this piece of software.

**Comment by djselbeck** [comment]
Nice catch. Without looking at the code I guess I have to escape the apostrophe before sending it to the server. It already got me once with an album title.

I will fix this.

**Comment by djselbeck** [comment]
Should be fixed. Tested with the following password:

> "'bla'password"
