### ISSUE TITLE
Feature request: add the possibility to switch the active audio output

### ISSUE THREAD

**Issue by sejerpz** [gateship-one/malp#73]
I've configured multiple audio output in MPD, one for each room of my house, it will be nice to have an icon to change the active audio output.

### I elaborate a bit my request.

I need to address 2 different needs:
1) Output the music to multiple speakers in different rooms at the same time. _Broadcast_
2) Output the music only to one speaker at a give time. _Follow me_

### My proposal

**(This feature should be presented to the user only if multiple sources are defined for a given profile).**
In the side panel add a section with:

```
Audio
   Follow Me
   Broadcast
```

When "follow me" is tapped a popup will be presented to the user with the available audio output, on tap the selected output will be enabled and all the others disabled

When "broadcast" is tapped a list with the available output sources and a checkbox will be presented to the user (like the current audio tab page in Profile), the user can check the wanted outputs to enabled / disable them

**Comment by transiti0nary** [comment]
I would be +1 for something similar where you could say quickly switch between having all your httpd outputs enabled for streaming setup or have only your local soundcard enabled for playback on your main audio system.

Both these features could be implemented as some sort of ability to create "output profiles" which can quickly be switched between from the sidebar?

**Comment by djselbeck** [comment]
You can select audio outputs from the server properties page. That's all you'll get for selecting audio outputs. 

What you propose is ridiculously out of scope for this application.

**Comment by sejerpz** [comment]
Hi,

>What you propose is ridiculously out of scope for this application
Can you elaborate a bit why? Is malp pourpose just managing different mpd playlists?

My setup is an eadless system without any local audio just to stream music in different rooms of my house. Going to the Output tab page deactivate the current output and activate a new one is a bit difficult and a long operation to do.

**Comment by djselbeck** [comment]
> Can you elaborate a bit why? Is malp pourpose just managing different mpd playlists or mpd servers?

Yes, you're correct. The purpose of MALP is to manage MPD with a good coverage of MPD features.

MALP covers a lot of them. What you're asking is a specialized edge case that may confuse the majority of MALP users and benefit only very few of them.

You could also write a script or a simple webpage on your MPD host to achieve the same thing. This does not necessarily belong in a MPD client.

**Comment by djselbeck** [comment]
https://github.com/gateship-one/malp/commit/659d94cb0b76b476bcb3e4060615d6a99312b53c

**Comment by sejerpz** [comment]
Yes, that's a step further. I just tested it and even if long press suffers from a discoverability point of view, it's useable. The only problem with that dialog is that it implements the "broadcast" functionality which in my opinion is less useful than the "follow me" feature.

Anyway thanks!

**Comment by sejerpz** [comment]
I worked a bit on a different UI that implements my idea but in the long press handler.

This is how it looks:

![malpoutputs](https://user-images.githubusercontent.com/1081062/31706193-609825fc-b3e8-11e7-8915-3db93e0a547d.png)

**Comment by djselbeck** [comment]
Looks ok for me. How does it work with long lists? Do they get scrollable (not that I think that anyone has more than fit on the screen :)?

**Comment by djselbeck** [comment]
Can you open a PR, then I'll check it out later

**Comment by sejerpz** [comment]
It's just a mockup done with code to see if the UI looks good for you.

In the next days I'll finish the implementation and I'll do the PR (it will take some time ;) )

**Comment by djselbeck** [comment]
Ah ok, could be tricky because the menu needs to be changed with a callback (on response of the server) and it has to be secured to ensure the menu is still there when the output results arrive.

**Comment by sejerpz** [comment]
I didn't have enough time to study the Loader class, perhaps a good approach is to show the menu' when the results arrive, meanwhile show a spinner to signal the loading takes a lot of time.

**Comment by djselbeck** [comment]
Maybe. A loader is not necessary. It is sufficient to call the getOutputs method of the MPDQueryHandler with the right callback response handler.

**Comment by sejerpz** [comment]
> It is sufficient to call the getOutputs method of the MPDQueryHandler 

Ok, I'll take a look. 

I'm still not sure what to do if there is just one output configured.

Options are: 

1. don't show the PopupMenu
2. show it anyway
3. popup a tip with "This function is available only when you have more than one audio output configured"

For now I'm towards option 1.

**Comment by djselbeck** [comment]
Merged
