### ISSUE TITLE
Feature request: show audio properties in now playing view

### ISSUE THREAD

**Issue by transiti0nary** [gateship-one/malp#74]
I was thinking, as someone who has a library containing various sample rates and bit depths, if it would be possible to have the option to display this information in the now playing view (MPDroid does this pretty well, for a reference of how it might look).

Just a little line of text in a format something like {BIT_DEPTH}bit {SAMPLE_RATE}khz {FORMAT} ({BIT_RATE}) for example

Thanks for the great app! If this and some of the other existing feature requests were implemented it would be near perfect!

**Comment by djselbeck** [comment]
Already implemented since the beginning. Scroll up the album cover (yeah it is hidden)
