### ISSUE TITLE
FR: Include metadata for fdroid

### ISSUE THREAD

**Issue by mueller-ma** [gateship-one/malp#75]
When providing metadata via a fastlane directory, fdroid automaticly shows them in the store. You dont need to install fastlane, just create the folder

Example: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US
Info: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

**Comment by djselbeck** [comment]
Commited the metadata and it should be picked up with the next release. At least if I haven't made any mistakes ;)

**Comment by mueller-ma** [comment]
It looks good, but there might be a problem with the (non-free) album pictures. Idk if they are allowed on F-Droid.

**Comment by djselbeck** [comment]
We have permission from Carbon Based Lifeforms to use them

**Comment by mueller-ma** [comment]
That doesn't mean they are free like in freedom, only for you, not for all other, e.g. fdroid.

**Comment by mueller-ma** [comment]
> The last important detail is that the texts in the app’s metadata file will override all other descriptive texts from Fastlane/Triple-T. That is specifically Name/AutoName, Summary, and Description. Once an app’s descriptive texts have been moved into the source repo, then file a merge request or issue to remove Summary and Description from the app’s metadata file.

from https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#directly-in-the-f-droid-repo

I can make a PR when it's on fdroid.

**Comment by djselbeck** [comment]
A PR for what?

**Comment by mueller-ma** [comment]
Description and summary from https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.gateshipone.malp.txt since it overrides the fastlane files.

**Comment by mueller-ma** [comment]
Can you do the same in Odyssey?

**Comment by djselbeck** [comment]
Thats the plan. We wanted to wait for MALPs release to check if everything is correctly done ;)

**Comment by mueller-ma** [comment]
Great!
