### ISSUE TITLE
GMPD-alike jump-to-queue from search

### ISSUE THREAD

**Issue by sellsky** [gateship-one/malp#8]
In Search, if a track found in the library is already enqueued, it could be preferable to jump to it rather than enqueue it once more. This is what GMPD acts like, and it turns out to be a very handy behaviour.

**Comment by sellsky** [comment]
How to speak with MPD.
First you do the usual search:
`search {type} {needle}`
As the user picks a track, check if its filename is in the queue:
`playlistfind filename {filename}`
If MPD provides any data in response, that means this track is enqueued at least once. Pick the first found id and jump:
`playid {id}`
That's it.

**Comment by djselbeck** [comment]
Thanks, I will look into this. Should be possible.

**Comment by djselbeck** [comment]
9f1899653c7101f22dc21987078e44221c644f95 implements this for the "Play song" option in the context menu.

**Comment by djselbeck** [comment]
Release with 1.1.0
