### ISSUE TITLE
NowPlayingView: when not connected to MPD service long tap on volume icon crash the app

### ISSUE THREAD

**Issue by sejerpz** [gateship-one/malp#80]
[issue_80_patch.txt](https://github.com/gateship-one/malp/files/1407065/issue_80_patch.txt)

Attached the one liner patch to fix the crash

**Comment by sejerpz** [comment]
[issue_80_patch.txt](https://github.com/gateship-one/malp/files/1407065/issue_80_patch.txt)

Attached the one liner patch to fix the crash

**Comment by djselbeck** [comment]
Fixed
