### ISSUE TITLE
Support android API Level 19

### ISSUE THREAD

**Issue by sejerpz** [gateship-one/malp#81]
Any interest in supporting android KitKat?

If yes I can volunteer to do it.

**Comment by djselbeck** [comment]
![dkur9tk](https://user-images.githubusercontent.com/1886122/32051477-0ab60cbc-ba55-11e7-8177-baa462b6fd30.png)

We explicitly decided against it because of current distribution values.

See here: [https://developer.android.com/about/dashboards/index.html](https://developer.android.com/about/dashboards/index.html)

**Comment by sejerpz** [comment]
![funny-goat-water-swimming](https://user-images.githubusercontent.com/1081062/32064872-613ed96c-ba7b-11e7-8044-b1b03b0d7f02.jpg)

14.5% it's not big but also not so low. Anyway I'll take a quick look since I've an old lenovo 4.4 and I'd like to run malp there.
I'll link a branch here just in case you want to take a look or someone else is interested.

**Comment by sejerpz** [comment]
This is my **dirty branch** in order to support lollipop: https://github.com/sejerpz/malp/tree/android_api_level_19

This version works on my old lenovo tablet at the expense of some ui regressions.

I'm asking for some advice to fix the header color of the menu' page, I haven't found a way to port that functionality: https://github.com/sejerpz/malp/commit/9a9e427fdb893e73dca4fe6c0e101618b6918eac#diff-e37e38b776bbeca08950d94521a58da4L27

**Comment by djselbeck** [comment]
After careful consideration I decided to not support this in my own time for two reasons.

First I do not want to encourage users to stay on old and unsupported Android versions that probably are vulnerable to a lot of security flaws.

Secondly I don't want to inject numerous code snippets to uphold backwards compatibility with potential UI regressions. 

Of course you can try to sync your branch with the master branch and use it on your own ;)
