### ISSUE TITLE
1.1.10 update on F-Droid, crashes on install and goes into boot loop

### ISSUE THREAD

**Issue by qouoq** [gateship-one/malp#84]
I believe the latest update of M.A.L.P. on F-Droid, version 1.1.10, is subject to the same bug as other recently updated softwares on F-Droid. To describe briefly, the update crashes the phone on installation, and crashes on boot, causing a reboot loop. Removing the app, then downgrading gives a working system.

More details may be found on the following bug reports:
- DAVdroid: https://forums.bitfire.at/topic/1603/replicant-lineage-1-9-1-causing-instant-crash-and-bootloops
- Yalp Store: https://github.com/yeriomin/YalpStore/issues/316

**Comment by djselbeck** [comment]
Yes, we are aware of it. It is a fault in android or androids build tools

See:

https://github.com/gateship-one/odyssey/issues/100

And:

https://forum.f-droid.org/t/some-app-updates-fail-to-install-and-force-f-droid-to-close/1556

You can install 1.1.11 apk from the release page on github or google play

**Comment by qouoq** [comment]
Thanks for the quick reply, I confirm the version 1.1.11 works on my device.

I added information about this issue on the following F-Droid issue: https://gitlab.com/fdroid/fdroiddata/issues/979, since it seems to be the best place to consolidate related discussions.
