### ISSUE TITLE
M3U Playlist Titles Ignored For Radio Streams

### ISSUE THREAD

**Issue by rsgca** [gateship-one/malp#85]
MALP uses the tail of a the radio stream URL as the title instead of the M3U title in the #EXTINF line.

For example, the M3U playlist includes
```
#EXTINF:-1,CBC Radio2 Vancouver
http://cbc_r2_vcr.akacast.akamaistream.net/7/773/451661/v1/rc.akacast.akamaistream.net/cbc_r2_vcr
```
MALP does not use "CBC Radio2 Vancouver" as expected; instead it uses "cbc_r2_vcr".

Is there a way to ensure MALP uses the specified title?

**Comment by djselbeck** [comment]
When playing the above radio stream MPD returns:

```
playlistinfo
file: http://cbc_r2_vcr.akacast.akamaistream.net/7/773/451661/v1/rc.akacast.akamaistream.net/cbc_r2_vcr
Name: CBC R2 VCR
Pos: 0
Id: 6

```

**Comment by rsgca** [comment]
Roger, thanks for the explanation! 

I think your commit [b8e59a8](https://github.com/gateship-one/malp/commit/b8e59a83eb9c037ddf2cc630ef26c883660123e2) will address my issue.

If no song title is available (like with streaming urls), show the name. If no name is available, show path.
