### ISSUE TITLE
Crash when browsing library on Play store version

### ISSUE THREAD

**Issue by transiti0nary** [gateship-one/malp#88]
I have been using MALP installed via F-Droid on a phone with a custom ROM etc, until yesterday I decided to return to stock ROM + Play store, to try Android O out.

After installing MALP from the Play store and adding a profile, I can browse my library for a short while until at some point it 'stops responding' (app closes and Android system dialogue comes up).

The background service / notification continues running, though.

The only way to get it to open without crashing is to clear app data, re-add the profile but eventually the problem re-appears.

I remember having this issue the last time I installed from the Play store, but as I switched to F-Droid shortly afterward I forgot about it -- and that was Android N so it doesn't seem related to moving to Oreo.

I can try and get a log file to give you more information if you let me know how to do so.

Btw, any link for donation towards this software? :)

**Comment by djselbeck** [comment]
I'm using AOSP 8.0 (Oreo) as well. My version should be equivalent to the Google Play version.

Perhaps something gets damaged with the ArtworkDatabase

A logcat output of the crash would be very helpful.

> Btw, any link for donation towards this software? :)

Thanks for asking ;), we are doing the development as a hobby in out free time without donations. Appreciation and friendly critic for our work is good enough for us

**Comment by transiti0nary** [comment]
[malp.log](https://github.com/gateship-one/malp/files/1549596/malp.log)

That's the relevant part of the logcat as far as I can tell

**Comment by djselbeck** [comment]
Thanks. It looks like an image is to big for the SQLite database. I encountered the same problem a hour ago.

We will change the way images are stored on the devices in the foreseeable future to store them directly on the filesystem. I'll try to fix the issues before. Images should be scaled down enough to prevent the issue from happening.

**Comment by djselbeck** [comment]
Can you try this APK check if it will still crash?

https://owncloud.djselbeck.de/index.php/s/SV7bOVQxS8DBnZc

**Comment by transiti0nary** [comment]
So far, so good. Used it for a few minutes with no issues.

**Comment by djselbeck** [comment]
No blobs are saved in the sqlite database anymore. so this bug is fixed with the next release.
