### ISSUE TITLE
'Connected with MPD server' notice blocks control buttons for a while

### ISSUE THREAD

**Issue by sellsky** [gateship-one/malp#9]
Every time i switch to the app, this notice 'Connected with MPD server' appears in the bottom of the screen blocking control buttons, so I have to wait for a few moments before I can press them, which is quite annoying, I don't think I need any notice at all unless there was an error, so may this notice be removed or placed somewhere else? Thank you.
1.0.8.
Android 5.1.1.

**Comment by djselbeck** [comment]
I was getting annoyed by it too. Removed it for now with: 8f25a973725c6dfa8191cc889afadcb569c4ef1f

**Comment by djselbeck** [comment]
Release with 1.1.0
