### ISSUE TITLE
Play song from library

### ISSUE THREAD

**Issue by Jucgshu** [gateship-one/malp#91]
Hi guys,

I'm trying to play songs directly from the library, and all it does when I click on the songs is giving a screen with all the song tags and the option to ```Add``` or ```Cancel```. Thus I wonder: with the ```+``` button in the album view, can we play the songs directly? Am I missing something?

Great work on the app btw. Really slick and well designed.

-j

**Comment by djselbeck** [comment]
You can hold down on a track and select the first menu entry "Play Song" ;)

Does this work for you?

**Comment by Jucgshu** [comment]
Hi @djselbeck thanks for the answer.

It works, but can it be defined as the default action?

**Comment by djselbeck** [comment]
Maybe as an option. I'll think about it. Maybe as append to playlist and play on a per song basis.

**Comment by Jucgshu** [comment]
The default action in most players is the clear the current playlist / song queue and directly play the selected song. Optionnally, one can choose to add the song to the playlist and keep the current song queue running.

Anyway great app, and thanks for your feedback.

**Comment by djselbeck** [comment]
The next version will feature a preference to select between actions (details, add (default) and play). 

Unfortunately the next release can be a while as I've redone the thread synchronization of the main MPD connection class and I'm not completely satisfied with it yet.

**Comment by gnome17** [comment]
The feature was released today. You can now select click to play a song in which case the song is added to queue and played immediately on click in the library.
