### ISSUE TITLE
FR: Single click play

### ISSUE THREAD

**Issue by gerroon** [gateship-one/malp#93]
Hi

It would be nice if it is possible to play songs with a single click when they are not in the playlist. I personbally use Mpd mainly for internet radio and generally it makes more sense to play the piece as soon as clicked on it given that a stream generally never ends, so adding playlist and playing from there is one work around.

**Comment by djselbeck** [comment]
That's personal preference. Others may like click to add, you like click to play.

**Comment by djselbeck** [comment]
Also,  duplicate of #91
