### ISSUE TITLE
FR: Share

### ISSUE THREAD

**Issue by gerroon** [gateship-one/malp#94]
Hi
It can be useful to share the current artist, song , station detail etc via the share menu. Mpdroid has this feature and it is very helpful but it is not developed anymore :(

**Comment by djselbeck** [comment]
I don't see any use for this. Also MALP is not MPDroid

**Comment by gerroon** [comment]
Well, sure, the share in Android has no use for anybody ever. They should just remove it from Android because someguy on github said there is no use for share.  And noone is ever said MALP is not MPDroid.

**Comment by djselbeck** [comment]
You're missing the point. I don't have anything against the share button. I don't see any use in sharing some random track metadata.

You should check your attitude. I am getting annoyed of users telling me what MPDroid did. If you don't like MALP don't use it. Stop complaining!

**Comment by gerroon** [comment]
Well here is a use case for "sharing" meta data.

You are listening a radio station, there is a track you like and you want to send this data to your favorite note taking app or some other ways to storage app. So that you can try to find more info on those later. 

There is no problem with users doing some comparative judgement. That is human nature we always have some reference point to start with. As a user I am not trying to annoy you with such comparison. It is natural to do some comparison when moving between different tools. It is not like M.A.L.P is a paradigm shift in how to access Mpd,  at least for now. It is kind of similar in function and maybe is taking a bit of a different direction. 

 Anyway like I said, my comparison was not about  trying to pull M.A.L.P in the direction of Mpdroid and annoy the developers of this tool.

thanks

**Comment by djselbeck** [comment]
Obviously I didn't thought about that. I'll consider this. 

Although a screenshot would also do ;)

**Comment by gerroon** [comment]
"Screenshot" is really what I do butit is a bit of work if you really want to save that in your note taking app (like cropping, resizing etc) and gets tedious while one the move.

Thanks for reconsidering.

**Comment by djselbeck** [comment]
Will be released with the next version ;)

**Comment by gerroon** [comment]
Awesome. Thanks and keep up the great work.
