### ISSUE TITLE
FR: Disable survival mode

### ISSUE THREAD

**Issue by gerroon** [gateship-one/malp#99]
Sorry for the catchy title but it is relevant.

It seems like M.a.l.p always wants to stay at the top of the tray bar or task bar (I do not know what is called actually) which creates friction and arms race between all apps trying to share the tray basically. M.a.l.p is the only app I get this super racing situation when it is open. WHat happens is that it stays on top, I open another app with media controls and that app sets itself on top then Malp want sto take over and the other app reacts etc which creates a crazy looking tray icons war. 

Yeah I would like Malp to be at the top as a user but not the cost of that situation. Then what happens is that it becomes hard to press any buttons in there because icons constantly moving around.

This is happening on Android Lollipop 5.1

thanks

**Comment by djselbeck** [comment]
Has to be this way. 

If you don't like the notification of MALP you need to disable it. I know that this seems aggressive but if the notification is not in the foreground android will kill it on new android versions. 

So with Google more and more prohibiting services to stay active in the background more and more apps will be using foreground applications. (E.g. Fitbit now has a permanent foreground notification active). 

You can read up on this here:

https://developer.android.com/about/versions/oreo/background.html#services

So if multiple applications are showing foreground notifications the Android system seems to screw up the order of notifications in last come top position or something more unpredictable.

To show to you that MALP is not doing anything evil you can read up here:

https://github.com/gateship-one/malp/blob/master/app/src/main/java/org/gateshipone/malp/application/background/NotificationManager.java#L142

and here

https://github.com/gateship-one/malp/blob/master/app/src/main/java/org/gateshipone/malp/application/background/NotificationManager.java#L331

**Comment by gerroon** [comment]
To understand the issue better, I thought that FG notification means anything that has a presence in the notification tray? But based on how you described it, it seems like being listed there is not enough, the app also has to be at the top of the list? 

Btw I am using Lollipop, I do not have an Oreo device so not sure if those restrictions apply to my version.

Anyway, my point was that constant chaning of the order of things contantly changing makes it a bit chaotic in the tray, and if I understand what you described correctly you are saying that there is no other way around. Ok, but I have many fg apps in the notification area and they do their business ok without trying to reach to the top all the time. 



thanks

**Comment by djselbeck** [comment]
> To understand the issue better, I thought that FG notification means anything that has a presence in the notification tray? But based on how you described it, it seems like being listed there is not enough, the app also has to be at the top of the list?

The position is not defined by the application. It is defined by the system. With newer android versions it seems to be more stable than with android 5 (I can reproduce this issue with two battling media players as well, as soon as one updates it notification).

And yes, a notification alone is not enough for a BackgroundService to survive. It needs to be a foreground notification. For services that need a constant tcp connection (in this case MPD) it is necessary for the service to stay alive. It is not really doing anything on the CPU as it is only waiting on a TCP socket for data from MPD and periodically (every 60 seconds) refreshing the status.

I guess that android was designed that usually only one application needs to be a foreground application as a user normally only plays back one media file.

**Comment by gerroon** [comment]
Thanks for taking your time to explain this issue. it makes sense now.
